#!/bin/bash

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cd $SCRIPT_DIR

LOG_FILE="${TMPDIR:-/tmp}/KubeLog-logs-$(date +"%Y_%m_%d_%H_%M_%S")-$$.log"

touch $LOG_FILE

function stub_logger() {
  echo "[$$][KubeLogScript] $1" >> $LOG_FILE
  syslog -s -k \
    Facility com.apple.console \
    Level Notice \
    Sender "KubeLogScript" \
    Message "[$$][KubeLogScript] $1"
}


stub_logger "Started in: $SCRIPT_DIR"
stub_logger "Logs in: $LOG_FILE"
stub_logger "Search for Java"

JH=`/usr/libexec/java_home -X |
  grep -A 1 "<key>JVMHomePath</key>" |
  grep -e "<string>" | sed "s@.*<string>\(.*\)</string>.*@\1@" |
  grep -v "jdk1." | grep jdk | head -n 1`
JH21=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
if [ -d "$JH21" ]; then
  stub_logger "Found java21: $JH21"
  export JAVA_HOME="$JH21"
  JAVACMD="$JAVA_HOME/bin/java"
elif [ -d "$JH" ]; then
  stub_logger "Found java: $JH"
  export JAVA_HOME="$JH"
  JAVACMD="$JAVA_HOME/bin/java"
else
  stub_logger "Use standard java"
  JAVACMD=java
fi

stub_logger "Start KubeLog"

"${JAVACMD}" \
		-Xdock:icon="../Resources/AppIcon.icns" \
		-Xdock:name="KubeLog" \
		-jar ./KubeLog.jar >> $LOG_FILE 2>&1
EXIT_CODE=$?

stub_logger "Stop KubeLog with code: $EXIT_CODE"

exit $EXIT_CODE
