name: Run tests
on: [push, pull_request]
jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run all test
        run: ./gradlew test
