name: Run tests
on: [push, pull_request]
jobs:
  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Run all test
        run: ./gradlew test
